version: "3.1"

services:
  dashboard:
    build:
      context: .
      dockerfile: dockerfile
    container_name: nfc_backend
    restart: always
    ports:
      - 11200:5000
    volumes:
      - ./nfc_backend:/root/nfc_backend
    environment:
      MONGO_URL: mongodb+srv://Admin:Admin%40123@cluster0.sq11ob9.mongodb.net/nfc_auth?retryWrites=true&w=majority&appName=Cluster0

